# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SonarQube & PMD & SpotBugs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

       # Install missing maven dependencies

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'


      - name: List jar Directories
        run: |
            find . -type d -name "install" | grep -v "/\." | sed 's|^./||'

      - uses: gradle/wrapper-validation-action@v2
    # Cache the Gradle dependencies (optional step to speed up builds)
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
            path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
                ${{ runner.os }}-gradle-

        # This step will use Gradle Wrapper from your repository which uses the version specified in gradle-wrapper.properties
      - name: Build with Gradle
        run: ./gradlew build --info --stacktrace --scan


      - name: List Target Directories
        run: |
            find . -type d -name "target" | grep -v "/\." | sed 's|^./||'
      - name: List Source Directories
        run: |
          find . -type d -name "src" | grep -v "/\." | sed 's|^./||'



      - name: Check directory
        run: |
            ls
            pwd

      - name: List Target Directories
        run: |
            find . -type d -name "target" | grep -v "/\." | sed 's|^./||'
      - name: List Source Directories
        run: |
          find . -type d -name "src" | grep -v "/\." | sed 's|^./||'
          

      - name: Run SpotBugs
        run: |
            wget -qO- https://github.com/spotbugs/spotbugs/releases/download/4.8.3/spotbugs-4.8.3.tgz | tar -xz

            java -jar spotbugs-4.8.3.tar -textui -xml -output spotbugs_report.xml gdx-ai/target
        #   mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: List files and folders
        run: ls -alh 

      - name: List files and folders
        run: ls -alh target


#      - name: Upload SARIF file
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: spotbugs-report.sarif


      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
        with:
          args: 
            -Dsonar.projectKey=${{ secrets.WSVD_SONAR_PROJECT_KEY }}  
            -Dsonar.java.binaries="target"


      - name: List files and folders
        run: ls -alh 

      - name: List files and folders
        run: ls -alh target

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-xml
          path: |
            target/spotbugsXml.xml
